repos:
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3.11

  - repo: local
    hooks:
      - id: pylint-dead-code
        name: pylint dead-code checks
        entry: pylint --disable=all --enable=W0611,W0612,W0101
        language: system
        types: [python]
        files: ^golem/
        exclude: ^golem/tests/
